# Generated by Django 5.2.8 on 2025-12-31 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_useraddress'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('category', models.CharField(choices=[('refrigerator', 'Refrigerator'), ('washing_machine', 'Washing Machine'), ('microwave', 'Microwave'), ('mixer', 'Mixer'), ('grinder', 'Grinder'), ('power_hob', 'Power Hob'), ('chimney', 'Chimney'), ('tower_fan', 'Tower Fan'), ('rice_cooker', 'E-Rice Cooker'), ('kettle', 'E-Kettle')], max_length=30)),
                ('brand', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('discount_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('stock', models.PositiveIntegerField(default=0)),
                ('rating', models.FloatField(default=0)),
                ('reviews_count', models.PositiveIntegerField(default=0)),
                ('image', models.URLField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
