# Generated by Django 5.2.8 on 2026-01-09 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_product_brand_alter_product_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_best_product',
            field=models.BooleanField(default=False),
        ),
    ]
